"$schema" = "https://starship.rs/config-schema.json"

format = """
[ 󰌪 ](bg:magenta fg:black)[](fg:magenta) \
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$nix_shell\
$zig\
$line_break\
$character"""

palette = "sageveil"

[palettes.sageveil]
black = "#101310"
red = "#9A6B6B"
green = "#959C70"
yellow = "#A69966"
blue = "#8A8493"
magenta = "#876f7f"
cyan = "#7F9476"
white = "#A8AFA6"
bright_black = "#262F26"
bright_red = "#B08585"
bright_green = "#9C9F7F"
bright_yellow = "#C6B67E"
bright_blue = "#A39DAC"
bright_magenta = "#947e8d"
bright_cyan = "#9AAB90"
bright_white = "#c3cdc0"
surface = "#1C211E"
overlay = "#212723"
highlight = "#241d21"
border = "#4E504C"
muted = "#8A928B"
dim = "#6F7B6F"

[character]
success_symbol = "[❯](fg:green)"
error_symbol = "[❯](fg:red)"
vimcmd_symbol = "[](fg:yellow)"

[directory]
format = "[ 󰝰 $path$read_only ]($style)"
style = "fg:green"
truncation_length = 3
truncation_symbol = ""
read_only = " 󰌾"
repo_root_style = "bold fg:bright_green"
repo_root_format = "[ 󰊢 $before_root_path]($style)[$repo_root]($repo_root_style)[$path$read_only ]($style)"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:border"
symbol = "·"

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "fg:bright_magenta"
symbol = ""

[git_status]
disabled = false
format = "($all_status( $ahead_behind) )"
style = "fg:yellow"
up_to_date = ""
untracked = "[?${count}](fg:dim)"
stashed = "[\\$${count}](fg:blue)"
modified = "[!${count}](fg:yellow)"
renamed = "[»${count}](fg:cyan)"
deleted = "[✘${count}](fg:red)"
staged = "[+${count}](fg:green)"
ahead = "[⇡${count}](fg:cyan)"
diverged = "[⇡${ahead_count}](fg:cyan)[⇣${behind_count}](fg:magenta)"
behind = "[⇣${count}](fg:magenta)"

[nix_shell]
format = "[ $symbol$name]($style)"
heuristic = true
style = "fg:blue"
symbol = " "

[zig]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = " "

# Languages

[c]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = " "

[elixir]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = " "

[elm]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = " "

[golang]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = " "

[haskell]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = " "

[java]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = " "

[julia]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = " "

[lua]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = " "

[nodejs]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = "󰎙 "

[nim]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = "󰆥 "

[rust]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = " "

[scala]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = " "

[python]
style = "fg:blue"
format = "[ $symbol$version]($style)"
disabled = false
symbol = " "

[conda]
style = "fg:blue"
format = "[ $symbol$environment]($style)"
disabled = false
symbol = "🅒 "
